---
version: '3'
services:
  app-test:
    image: app-test
    build:
      context: ./.
      dockerfile: Dockerfile
    environment:
      CAPYBARA_SERVER_HOST: app-test
    ports:
      - '3000:3000'
    networks:
      main:
        aliases:
          - app-test

  fast:
    image: wallarm/fast
    environment:
      WALLARM_API_TOKEN: ${TOKEN}
      WALLARM_API_HOST: api.wallarm.com
      CI_MODE: recording
      # TEST_RUN_POLICY_ID: 129
    ports:
      - '8080:8080'
    networks:
      main:
        aliases:
          - fast

  selenium:
    image: selenium/standalone-firefox:latest
    ports: ['4444:4444']
    logging:
      driver: none
    environment:
      http_proxy: http://fast:8080
    networks:
      main:
        aliases:
          - selenium

networks:
  main:
